# Generated by Django 5.2.1 on 2025-06-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_room_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='sent_at',
        ),
    ]
