# Generated by Django 5.2.1 on 2025-06-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_date_message_sent_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='date',
        ),
    ]
