# Generated by Django 5.2.1 on 2025-06-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_sent_at_message_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='sent_at',
        ),
    ]
