# Generated by Django 5.2.1 on 2025-06-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_date_message_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
